[4.0-7.9] [#2483] Fix current selected security section is not highlighted in the menu
wazuh/wazuh-kibana-app pull request #2567
Opened 2020-10-27 12:50 UTC by frankeros

Hello team, this PR resolves:

- Current section is not highlighted in the main Menu

closes [#2483](https://github.com/wazuh/wazuh-kibana-app/issues/2483)

2020-10-27 13:09 UTC, jsanchez91 requested changes

2020-10-27 13:09 UTC, jsanchez91 commented on public/redux/actions/securityActions.js
> + * Wazuh app - React component for registering agents.
Remember to change the description of the copyright block

2020-10-27 13:09 UTC, jsanchez91 commented on public/redux/reducers/securityReducers.js
> + * Wazuh app - React component for registering agents.
The same problem

2020-10-29 12:39 UTC, jsanchez91 commented
@frankeros,

After testing the code, I found this bug:
> When you leave the security section, the item "Users" remains selected
![selected_security_tab](https://user-images.githubusercontent.com/3064506/97574628-cf3fb580-19eb-11eb-9e74-7ba6065daecd.gif)

2020-10-29 18:51 UTC, frankeros commented
> @frankeros,
> 
> After testing the code, I found this bug:
> 
> > When you leave the security section, the item "Users" remains selected
> > ![selected_security_tab](https://user-images.githubusercontent.com/3064506/97574628-cf3fb580-19eb-11eb-9e74-7ba6065daecd.gif)

@jsanchez91 this bug was fixed in this [commit](https://github.com/wazuh/wazuh-kibana-app/pull/2567/commits/9755f9468168c1b7c4010e8d5407f2fa69ea565b)

2020-10-30 11:33 UTC, jsanchez91 approved these changes
LGTM! :tada:

2020-10-30 11:33 UTC, merged