Callout
wazuh/wazuh-kibana-app pull request #2635
Opened 2020-11-18 12:17 UTC by pablomarga

Hi team! I have added a callout when there aren´t any agents that shows the view to add an agent.
This closes [#2564](https://github.com/wazuh/wazuh-kibana-app/issues/2564)

2020-11-18 12:45 UTC, frankeros requested changes

2020-11-18 12:45 UTC, frankeros commented on public/components/common/welcome/overview-welcome.js
> +    console.log("erwe", this.props)
remove console.log

2020-11-18 13:03 UTC, pablomarga commented on public/components/common/welcome/overview-welcome.js
> +    console.log("erwe", this.props)
Removed, thx.

2020-11-18 18:09 UTC, Desvelao commented
Maybe, you could add vertical space between the callout and the panel?

2020-11-19 11:53 UTC, jsanchez91 approved these changes
LGTM!

2020-11-19 11:58 UTC, frankeros approved these changes
LGTM!

2020-11-19 12:03 UTC, merged