Bugfix/cluster delay error
wazuh/wazuh-kibana-app pull request #2651
Opened 2020-11-23 15:59 UTC by pablomarga

Hi team! This PR solves the delay problem restarting the cluster when you edit a rule.

Closes [#2640](https://github.com/wazuh/wazuh-kibana-app/issues/2640)

2020-11-27 10:05 UTC, jsanchez91 requested changes
Please check the requested changes and update the CHANGELOG file with the Issue.

Remember to update your branch with the last changes in the branch `4.0-7.9`

2020-11-27 10:05 UTC, jsanchez91 commented on public/components/common/restart-cluster-manager-callout.tsx
> +      this.showToast('success', `${data.restarted === 'cluster' ? 'Cluster was restarted': 'Manager was restarted'}`)
If the possible values of `data.restarted` are `cluster` or `manager` change the string template to:

```ts
`${data.restarted} was restarted`
```

2020-11-27 17:56 UTC, Desvelao commented on server/controllers/wazuh-api.js
> +          this.makeRequest(method, path, data, id, reply, token).then(console.log).catch(console.log);
I think we should log here, maybe.

2020-11-30 14:36 UTC, jsanchez91 approved these changes
LGTM!

2020-11-30 14:37 UTC, Desvelao approved these changes
LGTM!

2020-11-30 14:38 UTC, merged