[FEATURE] Added index pattern fields refreshing from events
wazuh/wazuh-kibana-app pull request #2661
Opened 2020-11-25 18:26 UTC by frankeros

Hi team! This resolves:

- Refresh index pattern fields when there are some unknown fields in the document viewer from Events.

Closes #2630

2020-11-27 13:10 UTC, Desvelao commented
I tested the PR, and it works.

The toast:
![image](https://user-images.githubusercontent.com/34042064/100452548-a4638280-30b9-11eb-8336-88bfb5a38b11.png)

And the field shows a `?` icon,  but after reloading the page, this disappears
![image](https://user-images.githubusercontent.com/34042064/100452798-2358bb00-30ba-11eb-8727-c1d960a3a28b.png)

2020-11-27 13:11 UTC, Desvelao approved these changes
LGTM!

2020-11-30 14:40 UTC, jsanchez91 requested changes

2020-11-30 14:40 UTC, jsanchez91 commented on CHANGELOG.md
> +- Improved management of index-pattern fields [#2630] (https://github.com/wazuh/wazuh-kibana-app/issues/2630)
Update the branch and move this to the 4014 revision

2020-11-30 15:35 UTC, jsanchez91 approved these changes
LGTM!

2020-11-30 15:35 UTC, merged