Feature/add warning when configuring new role mapping
wazuh/wazuh-kibana-app pull request #2876
Opened 2021-02-01 15:23 UTC by pablomarga

Hi team this PR adds a toast warning the user when configuring role mapping if run_as is set to false. 

![Captura de pantalla 2021-02-01 a las 16 22 13](https://user-images.githubusercontent.com/46006326/106478672-b989d280-64a9-11eb-8036-2b9eb426a4c6.png)

Closes #2851

2021-02-01 15:30 UTC, frankeros requested changes

2021-02-01 15:30 UTC, frankeros commented on public/components/security/roles-mapping/components/rule-editor.tsx
> +      showToast('warning', 'These changes will not take effect until run_as is activated in /usr/share/kibana/data/wazuh/config/wazuh.yml and the Kibana service is restarted');
the path could come from a constant, and you should add " and the Wazuh user has the `allow_run_as` as true

2021-02-02 08:53 UTC, Desvelao commented on public/components/security/main.tsx
> +      .catch(error => console.log('Hubo un error'))
Remove the log in Spanish and manage the error otherwise or do nothing in the `.catch`.

2021-02-04 10:14 UTC, Desvelao commented
I tested the PR and I found the callout is showing in all `Security` section tabs, like this:
![image](https://user-images.githubusercontent.com/34042064/106878311-166bcf80-66da-11eb-86ad-7db4aa325a2d.png)

Do we want to show this message in all tabs of the Security section or it should only appear in `Roles mapping` tab?

2021-02-04 14:39 UTC, frankeros commented
I tested it, works well but when you have the setting `run_as` as `true` the callout is displayed for a while and then it disappears.
It looks like the callout is displayed by default until the request for `allowedRunAs` is got.

2021-02-04 14:42 UTC, frankeros commented on public/components/security/main.tsx
> +              {allowRunAs !== API_USER_STATUS_RUN_AS.ENABLED && isNotRunAs()}
you could add another state to wait for the request to complete, maybe
```
{allowRunAs !== API_USER_STATUS_RUN_AS.ENABLED && !allowRunAsIsLoading && isNotRunAs()}
```

2021-02-05 13:55 UTC, frankeros approved these changes
LGTM!

2021-02-05 13:55 UTC, merged