Feature/2826 create index pattern configuration
wazuh/wazuh-kibana-app pull request #2985
Opened 2021-02-18 14:48 UTC by pablomarga

Hi team, this PR add the feature of creating new index pattern after the default one is changed in the settings module.

2021-02-18 21:05 UTC, asteriscos approved these changes
Tested as the issue described and found a strange behavior. When you first set a new index, it works well. BUT, after the **healthcheck**  if you try to set it back to the original one, it does not change the default index.

Steps to reproduce:

1. Set a **new default index** (a new one)
![image](https://user-images.githubusercontent.com/9343732/108423529-bbc48e80-7216-11eb-95d9-0323af271846.png)
![image](https://user-images.githubusercontent.com/9343732/108423553-c121d900-7216-11eb-937d-a11f14937d21.png)

2. Check it worked in **management->kibana->indexPatterns**
![image](https://user-images.githubusercontent.com/9343732/108423867-2c6bab00-7217-11eb-811f-bdce3287402e.png)

3. Set it back to the original `index-pattern`
![image](https://user-images.githubusercontent.com/9343732/108423932-42796b80-7217-11eb-8d95-dfdc56b4936d.png)

4. Check it didn't actually work
![image](https://user-images.githubusercontent.com/9343732/108424022-5e7d0d00-7217-11eb-8c5d-235c611c23ac.png)

2021-02-18 21:37 UTC, asteriscos requested changes
Please check my last message, as I detected a strange behavior after I approved the PR.

2021-03-02 13:58 UTC, frankeros commented on public/components/settings/configuration/components/bottom-bar.tsx
> +        <EuiButton onClick={() => window.location.href = '#/health-check'} size="s">Execute health check</EuiButton>
you should save the toast id and remove it when the button is clicked

2021-03-02 14:06 UTC, frankeros commented on public/components/wz-menu/wz-menu.js
> +      const data = filtered
`filtered` could be true as an empty array

2021-03-02 14:13 UTC, frankeros requested changes

2021-03-02 14:13 UTC, frankeros commented on public/services/resolves/get-ip.js
> +    let indexPatternFound = indexPatterns.find((indexPattern) => indexPattern.attributes.title === configuration.pattern);
`const` instead of `let`

2021-03-02 14:13 UTC, frankeros commented on public/react-services/pattern-handler.js
> +      let indexPatternFound = patternList.find((indexPattern) => indexPattern.title === pattern);
`const`

2021-03-02 14:56 UTC, Desvelao commented
It's working but this message is a little bit strange saying.
```
No valid index patterns were found, proceeding to create default ....
```
![image](https://user-images.githubusercontent.com/34042064/109666465-7fc2ef00-7b6f-11eb-8dae-50afd9d89e55.png)

2021-03-02 16:07 UTC, frankeros approved these changes
Amazing job! 
Congrats @pablomarga :tada:

2021-03-15 20:52 UTC, merged