2981/roles mapping unespected beahvior
wazuh/wazuh-kibana-app pull request #3028
Opened 2021-02-26 15:19 UTC by sortizowlh

Hi team,
This PR checks an invalid behavior that added a logical operator AND or OR without needed.

Closes: #2981

2021-03-01 20:21 UTC, frankeros requested changes
Tested locally :x: 

-- 

Adding both kind of filters from the UI editor and switch to JSON editor, is removing the user filter
![image](https://user-images.githubusercontent.com/26828184/109553948-65770b80-7ab2-11eb-9f77-f54e2ff90c62.png)
![image](https://user-images.githubusercontent.com/26828184/109554040-80498000-7ab2-11eb-86d7-2160d3cf4584.png)

2021-03-01 20:21 UTC, frankeros commented on public/components/security/roles-mapping/helpers/rule-editor.helper.ts
> +    if(rulesArray.length == 1){
this is causing bad behavior because is removing the `userRulesArray`

2021-03-01 20:21 UTC, frankeros commented on public/components/security/roles-mapping/helpers/rule-editor.helper.ts
> +    if(rulesArray.length == 1){
please add some unit test to this function with this uses cases
- Giving userRulesArray NO empty and rulesArray NO empty, should return an object with one `'OR'` array with both arrays as items with all items
- Giving userRulesArray with 1 item  and rulesArray empty, should return the single item
- Giving rulesArray with 1 item  and userRulesArray empty, should return the single item
- Giving rulesArray with 2 o more items  and userRulesArray empty, should return an object with one item equals to the `logicalOperator` (OR or AND) array with all items
 - Giving userRulesArray with 2 o more items  and rulesArray empty, should return an object with one `'OR'` array with all items

2021-03-03 11:42 UTC, sortizowlh commented
Testing behavior. When adding some code to the JSON editor, the visual editor keeps these changes.

2021-03-03 11:48 UTC, gabiwassan requested changes
Great job!
Just a simple comment

2021-03-03 11:48 UTC, gabiwassan commented on public/components/security/roles-mapping/helpers/rule-editor.helper.test.ts
> +    describe('Given a non null rules array and non null internal users array ', () => {
Here the title says that rules and internal users are null, but they are not. They are correct? Or maybe you can copy this test and create a new one with null values and cover this case 😄 

Great job!

2021-03-08 16:56 UTC, Desvelao approved these changes
LGTM!

2021-03-08 17:16 UTC, Desvelao commented on tsconfig.json
> +    "jsx": "react",
Is this necessary?

2021-03-08 17:18 UTC, Desvelao commented
The change should be added to `CHANGELOG.md` file.

2021-03-16 20:28 UTC, frankeros approved these changes
tested locally :heavy_check_mark: 
Great job :tada:

2021-03-17 08:22 UTC, pablomarga approved these changes
LGTM!

2021-03-18 14:51 UTC, Desvelao commented
## Changes
- Updated the branch with the last changes of `4.1-7.10` branch
- Added change into the changelog

2021-03-18 14:53 UTC, merged