Improve toast message when select default API
wazuh/wazuh-kibana-app pull request #3049
Opened 2021-03-03 18:55 UTC by pablomarga

Hi teams this PR improve the message when you select an API as default in settings.
Closes #2948

2021-03-09 13:16 UTC, Desvelao requested changes
Test ✅ 
Screenshot:
![image](https://user-images.githubusercontent.com/34042064/110475811-9c1bda00-80e1-11eb-81f9-8ec66526be74.png)

❗ Request changes:
- Add the change to `CHANGELOG.md` file 

❓ Suggestions:
- Maybe add some text about `API host`?

2021-03-16 14:44 UTC, CPAlejandro commented
I've tried it and it works perfectly. Nice job!

2021-03-18 11:01 UTC, Desvelao approved these changes

2021-03-18 14:56 UTC, Desvelao commented
## Changes
- Resolved conflicts

2021-03-18 14:58 UTC, merged