2966/unauthorized agents shown
wazuh/wazuh-kibana-app pull request #3075
Opened 2021-03-15 14:46 UTC by sortizowlh

Hi team!
This PR resolve both issues:
#2966 and #2986

2021-03-18 13:09 UTC, CPAlejandro commented
I am checking the PR and I have found the following error:
I have created a user with the policies that I show and when entering the / agents section of my user, it appears as the most active user, one to which I do not have permissions![image](https://user-images.githubusercontent.com/17100196/111630916-21467380-87f3-11eb-9941-e8913fb5cc55.png)
![image](https://user-images.githubusercontent.com/17100196/111631032-3cb17e80-87f3-11eb-8c66-c55c071bf1a7.png)

2021-03-18 13:40 UTC, Desvelao commented
I tested the PR, and it seems it working for me.

Screenshots:
![image](https://user-images.githubusercontent.com/34042064/111635007-59e84c00-87f7-11eb-8bc4-2d3237fcd491.png)
![image](https://user-images.githubusercontent.com/34042064/111635141-7be1ce80-87f7-11eb-9f2e-ba5aa25d46f4.png)
![image](https://user-images.githubusercontent.com/34042064/111635197-87cd9080-87f7-11eb-87c6-e247e2829c2d.png)
![image](https://user-images.githubusercontent.com/34042064/111635347-b3507b00-87f7-11eb-83c1-05f2a64c630b.png)


Could someone test it?

I am not sure what happened, but, why are there so many commits and files modified?

2021-03-19 14:06 UTC, gabiwassan requested changes
Just some comments! Great Job 👍🏼

2021-03-19 14:06 UTC, gabiwassan commented on public/controllers/agent/agents-preview.js
> +    }
This catch is not doing anything, can we add a toast to show the possible error?

2021-03-19 14:06 UTC, gabiwassan commented on public/kibana-integrations/kibana-vis.js
> +        vizPattern = JSON.parse(rawVis[0].attributes.kibanaSavedObjectMeta.searchSourceJSON).index;
Same here, in this case, we have hidden the errors. Maybe we can log this kind of error, it's not necessary to show a toast.

2021-03-19 19:31 UTC, closed without merging

2021-03-19 19:31 UTC, frankeros commented
moved to #3088