add link to documentation
wazuh/wazuh-kibana-app pull request #3126
Opened 2021-04-06 20:16 UTC by eze9252

Hi team,  

This resolve: 

- Add link to documentation "Checking connection with Manager" when you add a new agent.

![Captura de pantalla de 2021-04-06 16-17-25](https://user-images.githubusercontent.com/36004787/113772956-c326f500-96fb-11eb-9578-53d7ff3459d4.png)

How to test:

Agents > Deploy a new agent

2021-04-07 10:20 UTC, Desvelao commented
Add the change in `changelog.md` file.

2021-04-07 15:45 UTC, eze9252 commented
> Add the change in `changelog.md` file.

2021-04-09 21:01 UTC, frankeros commented on public/controllers/agent/components/register-agent.js
> +              <p style={pTextCheckConnectionStyle}>To check if the connection with the manager was successful, follow the <a href={urlCheckConnectionDocumentation} target="_blank">documentation.</a><
also, the text could be a little more friendly
`To verify the connection with the Manager, please follow this document.`

2021-04-13 13:35 UTC, gabiwassan requested changes

2021-04-13 13:35 UTC, gabiwassan commented on public/controllers/agent/components/register-agent.js
> +};
Could use `em` o `rem` units here? it's better for responsive renders.

2021-04-13 14:07 UTC, pablomarga approved these changes
LGTM!

2021-04-13 16:01 UTC, merged