Feature/add status and type in vulnerabilities table
wazuh/wazuh-kibana-app pull request #3196
Opened 2021-04-26 19:37 UTC by eze9252

Hi team, this resolve:

- Add fields STATUS and TYPE in vulnerabilities/inventory table
- Refactor in table component (adapting for use in other components)

2021-04-30 14:45 UTC, Desvelao commented on public/components/agents/vuls/inventory/table.tsx
> +          reload={isLoading}
This props in the original table, redo the request with the current table status, when `reload` prop change.

2021-04-30 15:26 UTC, Desvelao commented
I was testing the PR with another Wazuh manager branch and I found when exporting to CSV, there columns are missing and the CSV columns are not in the same order that the table in the app.
![image](https://user-images.githubusercontent.com/34042064/116717147-dfefd900-a9d8-11eb-85fe-ddab32ce236d.png)

2021-04-30 19:22 UTC, eze9252 commented on public/components/agents/vuls/inventory/table.tsx
> +          sorting={sorting}
I forgot delete this prop.

2021-04-30 19:57 UTC, eze9252 commented on public/components/agents/vuls/inventory/table.tsx
> +          searchTable={true}
Yes, I'm renaming the component to `TableWithSearchBardWzAPI`

2021-04-30 20:14 UTC, frankeros requested changes
The issue requirements indicate:

>  But no information will be provided on the status of the vulnerabilities displayed.

Remove `Status` and `Type` from columns and detail

2021-05-21 19:57 UTC, frankeros approved these changes

2021-06-15 12:51 UTC, merged