Fix errors in PDF reports
wazuh/wazuh-kibana-app pull request #3272
Opened 2021-05-19 14:02 UTC by pablomarga

Hi teams this PR solves: 

- Bug log collection looks double when generating a pdf in the configuration of an agent

2021-05-19 20:07 UTC, Machi3mfl approved these changes
Fixed, no more duplicated data.
<img width="795" alt="Screen Shot 2021-05-19 at 17 06 09" src="https://user-images.githubusercontent.com/6089438/118877341-b84bac80-b8c4-11eb-9251-30f1a781eeb5.png">

<img width="535" alt="Screen Shot 2021-05-19 at 17 06 33" src="https://user-images.githubusercontent.com/6089438/118877329-b4b82580-b8c4-11eb-94b0-1757d104d6f0.png">

2021-05-20 11:53 UTC, Desvelao commented on server/lib/reporting/printer.ts
> +    // 385 el width máximo inicial por columna
In english

2021-05-20 11:53 UTC, Desvelao commented on server/lib/reporting/printer.ts
> +    const widthCharacter = 5; //min width para un caracter
In english

2021-05-20 12:47 UTC, Desvelao commented on server/lib/reporting/printer.ts
> +      let column_length = tableRows[0][step].text.length * widthCharacter;
The logic to calculate the column width is only considering the first line instead of all lines. This could be a cause of possible bugs.

2021-05-20 12:48 UTC, Desvelao requested changes
Could you use `camelCase` for the variable names instead of `snake_case`?

2021-05-20 17:12 UTC, Desvelao commented on server/lib/reporting/agent-configuration.ts
> +          tabs: ['General','File limit', 'Disk quota','File size','Who data','Synchronization'],
This shouldn't be necessary

2021-05-21 10:15 UTC, Desvelao approved these changes

2021-05-24 10:21 UTC, merged