Add modal creating new rule/decoder
wazuh/wazuh-kibana-app pull request #3274
Opened 2021-05-20 09:55 UTC by pablomarga

Hi team this PR solves:

2021-05-20 11:56 UTC, CPAlejandro approved these changes
LGTM!

2021-05-20 13:41 UTC, pablomarga commented on public/controllers/management/components/management/ruleset/ruleset-editor.js
> +                                  showModal();
You are totally right, thanks! It has been already changed

2021-05-20 14:19 UTC, frankeros approved these changes
CR: LGTM!

2021-05-20 17:10 UTC, Desvelao requested changes
**Code Review**: 👀 ✅ 
**Testing**: ❌ 

- The displayed modal has a message with `Close Flyout`. We should fix this.

![image](https://user-images.githubusercontent.com/34042064/119020415-7e4ed900-b99e-11eb-9b6b-0aeaa173d578.png)

2021-05-24 09:24 UTC, Desvelao approved these changes
**Code Review**: ✅ 
**Testing**: ✅ 

Screenshots:
![image](https://user-images.githubusercontent.com/34042064/119326551-4c7d9100-bc82-11eb-93d8-e071fa506588.png)

2021-05-24 10:05 UTC, merged