Feature/implement error boundary hoc
wazuh/wazuh-kibana-app pull request #3367
Opened 2021-06-14 08:44 UTC by pablomarga

Hi team this PR add the ErrorBoundary hoc to react components.

2021-06-14 20:58 UTC, gabiwassan requested changes
Great job!
Just some comments. 
And check to apply prettier on all your changes. 💪🏼

2021-06-14 20:58 UTC, gabiwassan commented on public/components/agents/syscollector/main.tsx
> +function MainSyscollectorClass(props) {
Could be better like arrow functions
`const MainSyscollectorClass = (props) => {`

2021-06-14 20:58 UTC, gabiwassan commented on public/components/common/modules/main.tsx
> +export const MainModule = compose (withErrorBoundary,withReduxProvider) (class MainModule extends Component {
Check prettier here

2021-06-14 20:58 UTC, gabiwassan commented on public/components/common/welcome/agents-welcome.js
> +    );withErrorBoundary
Maybe type error?

2021-06-14 20:58 UTC, gabiwassan commented on public/components/management/cluster/cluster-visualization.js
> +function KibanaVisClass(props) {
Same here change for arrow functions

2021-06-15 12:01 UTC, frankeros approved these changes
LGTM!

2021-06-15 12:28 UTC, Machi3mfl approved these changes
LGTM!

2021-06-15 12:35 UTC, gabiwassan approved these changes
LGTM ! 🚀

2021-06-15 12:45 UTC, merged