Implement try catch strategy ManagementController
wazuh/wazuh-kibana-app pull request #3374
Opened 2021-06-16 15:31 UTC by Machi3mfl

Hi team,
This PR implement our new error handling strategy on ManagementController

2021-06-22 18:21 UTC, frankeros commented on public/controllers/management/management.js
> +    this.logger = new ErrorOrchestratorService();
it should be implemented with getErrorOrchestratorService(), right?

2021-06-22 18:21 UTC, frankeros commented on public/controllers/management/management.js
> +          message: error?.message,
different implementation than line 164

2021-06-22 18:21 UTC, frankeros commented on public/controllers/management/management.js
> +          message: error?.message,
different implementation than line 164

2021-06-22 18:21 UTC, frankeros commented on public/controllers/management/management.js
> +          title: error?.name,
different implementation than the others, the title could be undefined

2021-06-22 18:21 UTC, frankeros commented on public/controllers/management/management.js
> +        location: 'ManagementController',
`'ManagementController'` is repeated in all catch, I suggest set it in a const

2021-06-23 19:39 UTC, gabiwassan requested changes

2021-06-23 19:39 UTC, gabiwassan commented on public/controllers/management/management.js
> +      ErrorOrchestratorService().handleError(errorOptions);
Check the ultimates changes of `4.3-7.10` now you can use this service like this:
`getErrorOrchestrator().handleError(errorOptions);`

2021-06-28 16:43 UTC, gabiwassan approved these changes
LGTM! 👍🏼

2021-06-28 18:25 UTC, frankeros approved these changes
LGTM!

2021-06-30 19:20 UTC, merged