Implement try catch strategy Security
wazuh/wazuh-kibana-app pull request #3390
Opened 2021-06-23 15:57 UTC by pablomarga

Hi team,
This PR implement our new error handling strategy on Security section

2021-06-23 18:49 UTC, gabiwassan requested changes
Great job!! just some details. 💪🏼

2021-06-23 18:49 UTC, gabiwassan commented on public/components/security/policies/create-policy.tsx
>        return;
This return is not necessary

2021-06-23 18:49 UTC, gabiwassan commented on public/components/security/policies/policies-table.tsx
> +                    const options = {
Check indentation here (prettier 🤓)

2021-06-23 18:50 UTC, gabiwassan commented on public/components/security/roles/roles-table.tsx
> +  const columns = [
beautiful 😍

2021-06-24 19:08 UTC, gabiwassan approved these changes
LGTM ! 🚀

2021-06-29 16:30 UTC, Machi3mfl approved these changes

2021-06-29 16:30 UTC, Machi3mfl commented on public/components/security/main.tsx
> +      throw new Error(error);
I think is better only `throw` the error, without the `new`. Except, when set a custom message error.

2021-06-30 19:33 UTC, merged