Implement try catch strategy reporting
wazuh/wazuh-kibana-app pull request #3427
Opened 2021-07-01 18:41 UTC by Machi3mfl

Hi team,
This PR implement our new error handling strategy on the Ruleset section

Close #3426

2021-07-01 20:07 UTC, gabiwassan requested changes

2021-07-02 07:09 UTC, Desvelao commented on public/controllers/management/components/management/reporting/reporting-table.js
> +      Promise.all(results).then((completed) => {
**issue**: if there is some error in this `Promise.all`, the `catch` from the `try/catch` block doesn't capture the error.

**suggestion**: We should use `await`
```js
await Promise.all(results)
this.props.updateIsProcessing(true);
this.showToast('success', 'Success', 'Deleted successfully', 3000);
```

2021-07-02 07:11 UTC, Desvelao commented on public/controllers/management/components/management/reporting/reporting-table.js
> +        this.deleteReport(itemList);
**issue**: this method is asynchronous, should we wait until the execution is completed?

2021-07-02 08:02 UTC, Desvelao commented on public/controllers/management/components/management/reporting/reporting-table.js
> +            message: ` Error deleting report: ${error.message || error}`,
**nitpick**: Remove the space at the beginning of the `message` value.

2021-07-05 20:56 UTC, gabiwassan approved these changes
LGTM! 🚀

2021-07-09 14:47 UTC, asteriscos approved these changes
CR: :heavy_check_mark:

2021-07-13 12:59 UTC, merged