check if there are any changes on configuration settings
wazuh/wazuh-kibana-app pull request #3482
Opened 2021-07-15 10:28 UTC by sortizowlh

Hi team!
This PR resolves an issue that displayed a banner to save changes when the content of the field had not been changed.
Closes: #3337

2021-07-19 06:45 UTC, CPAlejandro commented
LGTM!

2021-07-19 06:46 UTC, CPAlejandro approved these changes
CR: LGTM!
Testing: LGTM!

2021-07-19 06:47 UTC, CPAlejandro requested changes
Changelog needs to be added

2021-07-19 07:59 UTC, CPAlejandro approved these changes

2021-07-19 20:05 UTC, gabiwassan requested changes

2021-07-19 20:05 UTC, gabiwassan commented on public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
> +  if(JSON.stringify(props.item.value) != JSON.stringify(value)){
Is a good practice to check this with `!==` 🚔

2021-07-20 13:18 UTC, gabiwassan approved these changes

2021-07-21 09:07 UTC, Desvelao commented
**issue**: I tested the PR and doesn't work. When changing some setting of list/array type, it doesn't detect the changes and the bottom bar to save/cancel changes doesn't appear. When changing some boolean setting, it can't return to its original value. I treat this problem on this PR https://github.com/wazuh/wazuh-kibana-app/pull/3458/files. 

**suggestion**: Maybe we could close the PR if the solution I did on the mentioned PR worked.

2021-07-21 09:59 UTC, pablomarga reviewed
Tested the PR and seems to be not working fine

2021-09-02 17:55 UTC, mpRegalado requested changes
None of the changes in the diff between branches provides any functionality and all seem to be just the result of applying Prettier.

It seems like the commit that fixed this issue has accidentally been included in another branch that has since been merged, the issue is no longer present in the base branch.

2021-09-02 18:03 UTC, closed without merging