Feature/pagination drilldown tables
wazuh/wazuh-kibana-app pull request #3544
Opened 2021-08-06 08:26 UTC by CPAlejandro

Hi guys,

In this PR we switch from basic tables to memory tables to be able to show the paginated tables.

![image](https://user-images.githubusercontent.com/17100196/128481062-8807e5fd-00e9-4e2c-9750-f6036cc7f2a7.png)

To test it we will only have to get into the Office module and go to the Panel tab

2021-08-06 08:49 UTC, sortizowlh approved these changes
Test: 🟢 
CR: 🟢

2021-08-06 09:16 UTC, eze9252 approved these changes
LGTM!

2021-08-06 10:11 UTC, mpRegalado requested changes

2021-08-06 10:11 UTC, mpRegalado commented on public/components/common/hooks/use-es-search.ts
> +  }, [indexPattern, query, filters, page, preAppliedAggs.buckets.terms.order]);
`preAppliedAggs` may not have a `buckets.terms.order` property as it is optional. It's probably best to set the dependency as simply `preAppliedAggs`

2021-08-09 09:41 UTC, mpRegalado approved these changes
CR: LGTM :heavy_check_mark: 
Testing : LGTM :heavy_check_mark:

2021-08-09 10:09 UTC, Desvelao approved these changes
**review**:
Code review ✅ 
Testing ✅

2021-08-09 10:41 UTC, merged