Disable apply button at initial state and move agents to their original position
wazuh/wazuh-kibana-app pull request #3605
Opened 2021-09-15 11:20 UTC by sortizowlh

Hi team!

When managing agents into a group generates an error, all the agents move to their original positions.
Also, the `Apply changes` button is disabled when all the agents are in their original position.

Solves: #3332

2021-09-15 11:49 UTC, asteriscos requested changes
Test: ❌

When one of the agents is added and the rest is not, it doesn't end in the right group column. Also, the `See full error` doesn't do anything. In addition, the number of `added` or `removed` items is not reset after the operation.

![Peek 2021-09-15 13-42](https://user-images.githubusercontent.com/9343732/133427633-003f0e92-2bd8-4c0a-a1d8-c2aa9b7e0282.gif)

2021-09-30 10:31 UTC, mpRegalado requested changes
The code performs the function required. Upon encountering an error, it reverts all the changes to its original state.
However, the way that it does so causes further errors to be logged into the console.

2021-09-30 10:31 UTC, mpRegalado commented on public/components/management/groups/multiple-agent-selector.tsx
> +    moveItem = (item, from, to, type) => {
This functions mutates the state. It doesn't seem to have been changed in this PR but it should be addressed

2021-09-30 10:31 UTC, mpRegalado commented on public/components/management/groups/multiple-agent-selector.tsx
> +              agents_list: itemsToSave.addedIds.toString(),
Deleting all agents from the `itemsToSave` list upon error means that the agents that caused the error in the first place are not in the group. So attempting to delete them causes another error. The final consequence is simply a console log, but the `failedIds` list should be updated when there is an error and used to filter what items are to be deleted.

2021-09-30 10:33 UTC, mpRegalado commented on public/components/management/groups/multiple-agent-selector.tsx
> +            failedIds.push(...addResponse.data.data.failed_ids);
This code is never executed. An error in the assignment of `addResponse` raises an exception that skips this section to the `catch` phase, meaning that `failedIds` is never updated.

2021-11-02 08:26 UTC, CPAlejandro approved these changes
CR and Testing: LGTM!

2021-11-05 12:57 UTC, merged