[FIX] [TELEMETRY] Hide the banner
wazuh/wazuh-kibana-app pull request #3709
Opened 2021-12-07 12:34 UTC by Desvelao

## Description
This PR hides the `telemetry` banner from UI and saves that the banner was seen to avoid the banner is displayed on the next times.

The status of if the banner was seen/dismissed of `telemetry` banner is stored in a saved object. This is persistent. For new environments, the attribute that controls this is not stored so the banner is displayed, if use the `Dismiss` button, store the flag in the saved objects for next times.

Moreover, the status is saved as a property i the `telemetry` plugin.

## Changed
  
- Hide the telemetry banner from UI and set a flag in the saved object that controls if the banner was seen and dismissed
- Changed the `wazuh` `public` `start` method to sync instead of `async` function

## Tests
- In new environments, the flag in a saved object of the `telemetry` banner is not set, so this is displayed. The PR, removes the banner from UI and sets the flag in the saved object.

Note:
Delete the `telemetry` object so this should be displayed again, or remove the indices `.kibana*` (where the telemetry saved object is stored) so it could test it again.

2021-12-07 12:40 UTC, gabiwassan approved these changes
LGTM!

2021-12-08 12:03 UTC, eze9252 approved these changes
LGTM!

2021-12-09 16:08 UTC, asteriscos requested changes
CR: :heavy_check_mark: 
Test: :x: 

Tested it with Open Distro and I'm getting this error before logging in

![image](https://user-images.githubusercontent.com/9343732/145432566-0bc31ce1-af76-4fec-99c6-447d718f49b4.png)

2021-12-10 10:25 UTC, Desvelao commented
### Changes
Now the telemetry banner is hidden and set the flag of the saved object when the frontend of the Wazuh app is to be mounted.

This means that the banner is visible if it was not dismissed before.

2021-12-10 16:41 UTC, asteriscos approved these changes
Test: :heavy_check_mark: 
CR: :heavy_check_mark:

2021-12-10 17:19 UTC, merged