Improve messages in the agent installation
wazuh/wazuh-kibana-app pull request #4040
Opened 2022-04-19 09:15 UTC by yenienserrano

**Description:**

Changes were made to the messages in the agent installation guide.

- From `You can predefine the Wazuh server address with the enrollment.dns setting` to `Define the Wazuh server IP address / name using the enrollment.dns setting below`

- From `Running this command on a host with an agent already installed upgrades the agent package without enrolling the agent. To enroll it, see the Wazuh documentation` to `Running this command will not enroll the agent if it is doing an upgrade. See Wazuh documentation.`

**Test:**

1. Navigate to `Agents`
2. Click on `Deploy a new agent`
3. Look at the changes

**Issues:**

Improve messages on agent installation walkthrough [#4037](https://github.com/wazuh/wazuh-kibana-app/issues/4037)
Improve messages in the agent installation instructions [#4036](https://github.com/wazuh/wazuh-kibana-app/issues/4036)

**Screenshot:**
![image](https://user-images.githubusercontent.com/63758389/163971268-c68186fc-2e2c-4054-9466-e18ff39e4f11.png)
![image](https://user-images.githubusercontent.com/63758389/163971297-b3e84d25-1796-47d6-846b-6901a4cd4fe1.png)

2022-04-19 10:08 UTC, AlexRuiz7 requested changes

2022-04-19 10:08 UTC, AlexRuiz7 commented on public/controllers/agent/components/register-agent.js
>                        <EuiLink href="https://documentation.wazuh.com/current/user-manual/registering/index.html">
There is a missign requirement on #4036 

> Also, the link to the documentation should open a new tab in the browser.

Add `target="_blank"` to this link, as seen [here](https://codesandbox.io/s/fcgt4y?file=/demo.js:198-213).

2022-04-19 10:57 UTC, AlexRuiz7 approved these changes
LGTM!

2022-04-20 09:17 UTC, yenienserrano commented
Updated proposal
![image](https://user-images.githubusercontent.com/63758389/164195079-cf54d249-cfc5-4260-89b6-45a3ddb1c3f2.png)

2022-04-20 10:36 UTC, yenienserrano commented
Updated proposal
![image](https://user-images.githubusercontent.com/63758389/164212852-068a8edc-58c4-43a2-a3ec-a2c56e07f7c2.png)

2022-04-27 13:56 UTC, Mayons approved these changes

2022-04-27 16:11 UTC, yenienserrano commented
Updated issue
- #4036

![image](https://user-images.githubusercontent.com/63758389/165563510-73aceae6-ecb4-48b9-aa81-4af9a1a869fc.png)

2022-04-28 06:32 UTC, merged