Empty file upload
wazuh/wazuh-kibana-app pull request #4176
Opened 2022-05-27 15:16 UTC by yenienserrano

**Description:**

When trying to import an empty file in rules or decoders, there was no information, it let you upload it but it had no effect, I added a warning to let the user know that he is uploading an empty file and not to let him upload it.

**Test:**

1. Navigate to `Management/rules or decoders`
2. Try uploading an empty file
3. See the warning

**Issue:**

- #4059 

**Screenshot:**

![image](https://user-images.githubusercontent.com/63758389/170724585-0ac2c45e-9f16-4f80-9c56-62edc663966f.png)

2022-05-27 19:38 UTC, Mayons95 commented
Test OK

Decoders:
https://user-images.githubusercontent.com/104914131/170778687-bc88cb86-f1d9-41e5-b6cb-56c01c892608.mp4

Rules:
https://user-images.githubusercontent.com/104914131/170778906-cc28f8e0-b1a2-4835-8f38-c17140c61530.mp4

2022-06-02 09:52 UTC, AlexRuiz7 requested changes

2022-06-02 09:52 UTC, AlexRuiz7 commented on CHANGELOG.md
> +- Fixed import of an empty rule or decoder file [#4176](https://github.com/wazuh/wazuh-kibana-app/pull/4176)
Must be changed to the 4.3.4 section.

2022-06-02 10:40 UTC, AlexRuiz7 approved these changes
LGTM!

2022-06-02 10:45 UTC, asteriscos approved these changes
Nitpick: I would change the message to something kinder, like "Please remove uploaded empty files to continue"
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 
![Screenshot from 2022-06-02 12-42-31](https://user-images.githubusercontent.com/9343732/171612806-616e1413-05aa-46dc-9da2-e61542659c25.png)

2022-06-02 10:58 UTC, merged