Adding all the components of security-events-dashboard
wazuh/wazuh-kibana-app pull request #4371
Opened 2022-07-29 15:36 UTC by Mayons95

Adding all the components of the different's modules

2022-07-29 18:47 UTC, mauceballos approved these changes

2022-08-01 18:25 UTC, mauceballos requested changes

2022-08-01 18:25 UTC, mauceballos commented on test/performance/modules/mitre-attack.module-dashboard.js
the name of the file should be "mitre-attack-module-dashboard.js"?

2022-08-03 12:53 UTC, asteriscos approved these changes
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 

![image](https://user-images.githubusercontent.com/9343732/182612507-f1710c52-52cb-48a1-a398-0ef32f38a6c3.png)

2022-08-03 12:53 UTC, merged