add test cases for GDPR && PCI-DSS modules
wazuh/wazuh-kibana-app pull request #4374
Opened 2022-08-02 13:59 UTC by mauceballos

add test cases for GDPR && PCI-DSS Modules and your tabs
* Dashboard
* Control
* Events

2022-08-02 15:43 UTC, Mayons95 commented on test/performance/modules/GDPR-module-dashboard.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 requested changes
See the comments on the files

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/GDPR-module-events.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/NIST-module-controls.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/NIST-module-dashboard.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/NIST-module-events.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/PCI-DSS-module-controls.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/PCI-DSS-module-dashboard.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:45 UTC, Mayons95 commented on test/performance/modules/PCI-DSS-module-events.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
This should be in the same line

2022-08-02 15:54 UTC, Mayons95 approved these changes

2022-08-03 18:11 UTC, mauceballos commented on test/performance/modules/GDPR-module-dashboard.js
> +    await commands.wait.byCondition("!isNaN(parseInt(document.querySelector('.statWithLink').innerHTML))", WAIT_TIMEOUT)
mmm, nop, shouldn't.

2022-08-08 13:54 UTC, mauceballos commented
**GDPR**  Module

>       - Control
>       - Dashboard
>       - Events
>       
> <details>
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-GDPR-module-controls-js-2022-08-08-10-25-49-pages-html-2022-08-08-10_29_07](https://user-images.githubusercontent.com/76791841/183430274-2ae66415-6f65-44af-b868-810b9d5065fb.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-GDPR-module-controls-js-2022-08-08-10-25-49-pages-localhost-GDPR-module-Controls-index-html-2022-08-08-10_29_22](https://user-images.githubusercontent.com/76791841/183430270-4b954a49-19a8-49a8-884b-bfa69053a79a.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-GDPR-module-controls-js-2022-08-08-10-25-49-pages-localhost-GDPR-module-Dashboard-index-html-2022-08-08-10_29_38](https://user-images.githubusercontent.com/76791841/183430264-391f63e1-c4ab-4712-8648-a92621410d4f.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-GDPR-module-controls-js-2022-08-08-10-25-49-pages-localhost-GDPR-module-Events-index-html-2022-08-08-10_29_52](https://user-images.githubusercontent.com/76791841/183430252-3b8abff5-df90-48ab-bed0-7208b5b08465.png)
> 
>  </details>



**PCI-DSS**  Module

>       - Control
>       - Dashboard
>       - Events
> 
> <details>
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-PCI-DSS-module-controls-js-2022-08-08-10-47-01-pages-html-2022-08-08-10_50_47](https://user-images.githubusercontent.com/76791841/183434077-0d6301d7-73e7-4988-9546-7aa85ac98b9e.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-PCI-DSS-module-controls-js-2022-08-08-10-47-01-pages-localhost-PCI-DSS-module-Controls-index-html-2022-08-08-10_50_38](https://user-images.githubusercontent.com/76791841/183434089-b943673a-9b43-46f7-8269-093761702185.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-PCI-DSS-module-controls-js-2022-08-08-10-47-01-pages-localhost-PCI-DSS-module-Dashboard-index-html-2022-08-08-10_50_28](https://user-images.githubusercontent.com/76791841/183434092-b37acdc4-4b76-4410-a5fc-b119e4101128.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-PCI-DSS-module-controls-js-2022-08-08-10-47-01-pages-localhost-PCI-DSS-module-Events-index-html-2022-08-08-10_50_15](https://user-images.githubusercontent.com/76791841/183434100-759212a8-fd70-43db-b99c-ee3491bd47cd.png)
> 
>  </details>

 

**NIST** Module

>       - Control
>       - Dashboard
>       - Events
> 
> <details>
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-NIST-module-controls-js-2022-08-08-10-36-39-pages-html-2022-08-08-10_40_14](https://user-images.githubusercontent.com/76791841/183432022-12f153f4-940a-4d0c-b7b3-947df00f0111.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-NIST-module-controls-js-2022-08-08-10-36-39-pages-localhost-NIST-800-53-module-Controls-index-html-2022-08-08-10_40_37](https://user-images.githubusercontent.com/76791841/183432018-5d7fd6ef-45b7-4df5-bd40-398cbd17bfc4.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-NIST-module-controls-js-2022-08-08-10-36-39-pages-localhost-NIST-800-53-module-Dashboard-index-html-2022-08-08-10_40_51](https://user-images.githubusercontent.com/76791841/183432013-7b398a3d-00e7-48bc-899e-323222950c90.png)
> 
> ![screencapture-file-home-mauri-repoPerformance-wazuh-kibana-app-test-performance-modules-sitespeed-result-NIST-module-controls-js-2022-08-08-10-36-39-pages-localhost-NIST-800-53-module-Events-index-html-2022-08-08-10_41_03](https://user-images.githubusercontent.com/76791841/183432007-dd07e1a1-4e45-476a-90ef-56ff3c957714.png)
> 
>  </details>

2022-08-08 14:11 UTC, closed without merging