Add delete sample data to modules
wazuh/wazuh-kibana-app pull request #4441
Opened 2022-09-05 18:57 UTC by mauceballos

fix test case

2022-09-06 18:49 UTC, Mayons95 requested changes
Review the commented code

2022-09-06 18:49 UTC, Mayons95 commented on test/cypress/cypress/integration/step-definitions/settings/sample-data/add-remove-sample-data.when.js
> +  // cy.log(titleStatus)
Please delete these commented log lines!

2022-09-06 18:53 UTC, mauceballos commented on test/cypress/cypress/integration/step-definitions/settings/sample-data/add-remove-sample-data.when.js
> +  // cy.log(titleStatus)
Done

2022-09-07 14:02 UTC, Mayons95 approved these changes

2022-09-07 17:47 UTC, Machi3mfl approved these changes
LGTM!

2022-09-07 17:53 UTC, merged