Upload file for `customization.logo.*` settings
wazuh/wazuh-kibana-app pull request #4504
Opened 2022-09-13 09:53 UTC by Desvelao

# Description

# Changes
Add endpoints to manage the upload/deletion
  - Upload: `PUT /utils/configuration/files/{key}`
  - Deletion: `DELETE /utils/configuration/files/{key}`

Add plugin setting type: filepicker
Add filepicker input form component
Display the customized image in `Settings/Configuration`
Add a button to remove the customized image

Closes #4426 

**Screenshots**

TODO

**Tests**

TODO

2022-09-14 18:25 UTC, asteriscos commented
### Different aspect ratio example

![image](https://user-images.githubusercontent.com/9343732/190233032-7049903e-bdf1-4fa9-bcc5-6ff3f244405c.png)

2022-09-16 18:27 UTC, asteriscos commented
## Pending

- [ ] Clear the file picker state when the file is uploaded

![image](https://user-images.githubusercontent.com/9343732/190707102-916b4379-7fd1-40db-bb20-e4e24e31fde0.png)

2022-09-23 08:40 UTC, Desvelao commented
# Update

- Update the development branch with the last changes of the base branch.

2022-10-06 08:08 UTC, Desvelao commented
# Requirements
Yesterday, in a sync meeting, we decide to get the file extension from the buffer instead of the current logic that send the file and the extension as another field.

2022-10-06 09:19 UTC, Desvelao commented
# Update
- Changed as the file extension was gotten when uploading the file. Now, it gets from the file buffer.
  - Create a service to get the file extension
  - Add some tests for the service
  - Remove the previous logic and adapt to use the service

2022-10-06 09:30 UTC, Desvelao commented
# Update
- Update the development branch with the base branch

2022-10-20 07:42 UTC, yenienserrano approved these changes
LGTM

2022-10-26 08:08 UTC, AlexRuiz7 commented on common/constants.ts
> +// Customization
Default 1 MB (actual value is in bytes)

2022-10-26 10:04 UTC, Desvelao commented
> Would you have to change to the branch you are merging to?

Changed.

2022-10-26 10:27 UTC, AlexRuiz7 requested changes

2022-10-26 10:34 UTC, Desvelao commented on public/components/settings/configuration/components/categories/components/show-toasts.tsx
> +	  title: 'This setting requires you to reload the page to take effect.',
The messages were not changed, they only were moved to another file, buy I will change the message with your suggestion.

2022-10-26 11:29 UTC, Desvelao commented on public/components/settings/configuration/components/categories/components/show-toasts.tsx
> +import _ from 'lodash';
Removed.

2022-10-26 11:29 UTC, Desvelao commented on public/components/settings/configuration/components/categories/components/show-toasts.tsx
> +	  title: 'This setting requires you to reload the page to take effect.',
Changed.

2022-10-26 11:29 UTC, Desvelao commented on public/components/settings/configuration/components/categories/components/show-toasts.tsx
> +	  title: 'You must execute the health check for the changes to take effect',
Changed.

2022-10-26 11:29 UTC, Desvelao commented on public/components/settings/configuration/configuration.tsx
> +import _ from 'lodash';
Removed.

2022-10-26 11:29 UTC, Desvelao commented on public/components/settings/configuration/configuration.tsx
> +import { EpluginSettingType, PLUGIN_PLATFORM_NAME, PLUGIN_SETTINGS, PLUGIN_SETTINGS_CATEGORIES, UI_LOGGER_LEVELS, WAZUH_ROLE_ADMINISTRATOR_NAME } from '../../../../common/constants';
Removed.

2022-10-26 11:31 UTC, Desvelao commented on public/components/settings/configuration/configuration.tsx
> +          }
It couldn't replicate it. Maybe some previous change doesn't cause this problem anymore.

2022-10-26 11:33 UTC, Desvelao commented
# Update
- Fixed a problem with an unexpected attribute for the input of type number.
- Fixed a problem when removing the configuration for `customization.logo.reports` that displayed the original logo when should not.

2022-10-26 11:39 UTC, Desvelao commented on public/components/settings/configuration/components/categories/components/show-toasts.tsx
> +	  title: `You must restart ${PLUGIN_PLATFORM_NAME} for the changes to take effect`,
Changed.

2022-10-26 11:39 UTC, Desvelao commented on public/components/settings/configuration/configuration.tsx
>  import { getToasts } from '../../../kibana-services';
Removed.

2022-10-26 14:37 UTC, AlexRuiz7 commented on common/services/file-extension.ts
> +		case '3c3f':
I did some research and looks like `3c73` is also a valid file signature for SVG files.

Lots of examples [here](https://www.w3schools.com/graphics/svg_examples.asp). Copy-paste and remove the HTML tags:

```xml
<svg height="400" width="450">
<path id="lineAB" d="M 100 350 l 150 -300" stroke="red" stroke-width="3" fill="none" />
  <path id="lineBC" d="M 250 50 l 150 300" stroke="red" stroke-width="3" fill="none" />
  <path d="M 175 200 l 150 0" stroke="green" stroke-width="3" fill="none" />
  <path d="M 100 350 q 150 -300 300 0" stroke="blue" stroke-width="5" fill="none" />
  <!-- Mark relevant points -->
  <g stroke="black" stroke-width="3" fill="black">
    <circle id="pointA" cx="100" cy="350" r="3" />
    <circle id="pointB" cx="250" cy="50" r="3" />
    <circle id="pointC" cx="400" cy="350" r="3" />
  </g>
  <!-- Label the points -->
  <g font-size="30" font-family="sans-serif" fill="black" stroke="none" text-anchor="middle">
    <text x="100" y="350" dx="-30">A</text>
    <text x="250" y="50" dy="-10">B</text>
    <text x="400" y="350" dx="30">C</text>
  </g>
  Sorry, your browser does not support inline SVG.
</svg>
```

![image](https://user-images.githubusercontent.com/15186973/198055884-973bc0bb-9484-41ab-8ed4-831c85aaa4c3.png)

2022-10-26 14:37 UTC, AlexRuiz7 requested changes
Errors during testing:

- Delete file: 400 Bad Request
![Screenshot from 2022-10-26 16-17-18](https://user-images.githubusercontent.com/15186973/198050935-0ee3b2ac-5e6e-46ab-ae3d-04c3f562e1aa.png)


- Upload valid SVG file: 400 Bad Request
![image](https://user-images.githubusercontent.com/15186973/198051108-5aa2fb9e-3f17-4ac5-96ef-5776b2214e78.png)

2022-10-26 15:22 UTC, Mayons95 reviewed
TR: 
<details>
[Screencast from 26-10-22 10:34:07.webm](https://user-images.githubusercontent.com/104914131/198067322-c363fa7c-7d62-4fc6-974c-4b5dd74f9345.webm)


[Screencast from 26-10-22 10:49:12.webm](https://user-images.githubusercontent.com/104914131/198067359-6f4c38fd-87d7-46d3-8cbe-53edb79ae8b7.webm)




</details>

2022-10-26 15:40 UTC, Desvelao commented
# Update
- Change the layout of the filepicker input and the logo with the button to remove the configuration.

**Screenshots**
:computer: Desktop
![image](https://user-images.githubusercontent.com/34042064/198071385-8b53f951-7097-4d96-ad5f-c2d5fe9d035d.png)
![image](https://user-images.githubusercontent.com/34042064/198071460-d0078097-597b-40bd-b8a6-94c3be2ea7e2.png)

:iphone: Mobile
![image](https://user-images.githubusercontent.com/34042064/198071628-4770c818-cbe5-4dc9-a56b-e1d463f0e1c6.png)
![image](https://user-images.githubusercontent.com/34042064/198071571-43ef1a93-f8e0-4985-8deb-668b5f5077e9.png)

2022-10-26 17:02 UTC, Mayons95 commented
TR: :heavy_check_mark: 

<details>

[Screencast from 26-10-22 13:57:01.webm](https://user-images.githubusercontent.com/104914131/198089786-a29fb484-982c-42e0-ad0f-c82f19a8010d.webm)

[Screencast from 26-10-22 13:58:09.webm](https://user-images.githubusercontent.com/104914131/198089828-6eacda3b-6d4d-49dc-89bd-95aedecb8795.webm)


</details >

2022-10-26 17:07 UTC, Mayons95 submitted a review, later dismissed
LGTM

2022-10-27 08:50 UTC, yenienserrano approved these changes
LGTM

2022-10-27 10:06 UTC, yenienserrano submitted a review, later dismissed

2022-10-27 13:22 UTC, Mayons95 commented
TR Comments:
We performed a script with @Desvelao and @asteriscos to test the API file upload, I left the script here, to use it, it's necessary to update the cookie value.

[script.tar.gz](https://github.com/wazuh/wazuh-kibana-app/files/9879764/script.tar.gz)

2022-10-27 13:35 UTC, Mayons95 approved these changes
TR: :heavy_check_mark: 
LGTM

2022-10-28 08:59 UTC, Desvelao commented
Some problems found by @AlexRuiz7 

**Environment: Kibana 7.10.2 development mode.**

## The endpoint to remove the configuration for the `customization.logo.*` setting doesn't work.
Endpoint: `DELETE /utils/configuration/files/{key}`

We were researching and saw that could be caused by the development proxy (not using the `--no-base-path` when starting the server) and accessing using the `5601` port instead of the mentioned port `5603` in the logs of the platform. We do not know the reason for the problem.

Others requests with the same HTTP verb (`DELETE`) fail too.
![image](https://user-images.githubusercontent.com/34042064/198526460-92802b1e-21da-4a85-ace5-7b33957bb882.png)

## Some custom logos are not visible when using SVG images.
This problem happens in:
- custom image preview in `Settings/Configuration`
- plugin menu

This is caused because the SVG image has not defined the `height` and `width` properties.
![image](https://user-images.githubusercontent.com/34042064/198527050-9122a7e2-d693-495a-bd81-ede4efa17977.png)

If these properties are added, the problem disappears.
![image](https://user-images.githubusercontent.com/34042064/198527168-65a99e7b-49b5-43e7-8ecb-c4835dd4e237.png)
![image](https://user-images.githubusercontent.com/34042064/198527231-30131295-18bc-499e-a401-5c408c642124.png)

@AlexRuiz7 reported that by using the same SVG for other settings as `customization.logo.healthcheck` and `customization.logo.sidebar`, the images are displayed correctly. This means that some styles could be affecting how the browser should render the image.

### Research - Custom image preview in `Settings/Configuration`

I found that if the `width: auto` CSS property is removed from the element style, the image is displayed correctly. This property is set by the `EuiImage` component when the `size` property is defined as a number https://github.com/elastic/eui/blob/v29.3.2/src/components/image/image.tsx#L140.

EDIT: I pushed a commit to solve this problem.

### Research -  Plugin menu

EDIT: I pushed a commit to solve this problem.

2022-10-28 09:02 UTC, Desvelao commented
In a meeting with @asteriscos , we saw a problem related to the browser cache and the `customization.logo.*` settings used in the frontend UI.

How to replicate:
1. Upload an image with some extension (`jpg`, `png`, `svg`)
2. Upload another image with the same extension as step 1. The UI display doesn't change and displays the image of step one. Cleaning the browser cache solves the problem.

We want to research a solution that does not implicate cleaning the browser cache and minimizes the users.

2022-10-28 09:23 UTC, Desvelao commented
> In a meeting with @asteriscos , we saw a problem related to the browser cache and the `customization.logo.*` settings used in the frontend UI.
> 
> How to replicate:
> 
> 1. Upload an image with some extension (`jpg`, `png`, `svg`)
> 2. Upload another image with the same extension as step 1. The UI display doesn't change and displays the image of step one. Cleaning the browser cache solves the problem.
> 
> We want to research a solution that does not implicate cleaning the browser cache and minimizes the users.

Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4504/commits/ccd57ca7c2d00ec43eb199f452ddf5a1b42b5188.

2022-10-28 09:35 UTC, asteriscos commented
> > In a meeting with @asteriscos , we saw a problem related to the browser cache and the `customization.logo.*` settings used in the frontend UI.
> > How to replicate:
> > 
> > 1. Upload an image with some extension (`jpg`, `png`, `svg`)
> > 2. Upload another image with the same extension as step 1. The UI display doesn't change and displays the image of step one. Cleaning the browser cache solves the problem.
> > 
> > We want to research a solution that does not implicate cleaning the browser cache and minimizes the users.
> 
> Solved in [ccd57ca](https://github.com/wazuh/wazuh-kibana-app/commit/ccd57ca7c2d00ec43eb199f452ddf5a1b42b5188).

Now when an image is uploaded, the path saved in the configuration includes a version number to handle browser cache issues.
`customization.logo.app: "custom/images/customization.logo.app.png?v=1666948554416"`

2022-10-28 09:58 UTC, AlexRuiz7 approved these changes
- Code review: ✔️ 
- Test: ✔️

2022-10-28 09:59 UTC, Mayons95 approved these changes
LGTM 
TR: :heavy_check_mark: 
Test with the last implemented changes

2022-10-28 10:00 UTC, merged