Initialize Wazuh plugin with custom logos
wazuh/wazuh-kibana-app pull request #4539
Opened 2022-09-16 12:10 UTC by asteriscos

# Description

Initialize Wazuh plugin with custom logos

Closes #4538

2022-09-19 19:04 UTC, matiasmoreno876 approved these changes
CR : LGTM ✅

2022-09-20 11:58 UTC, AlexRuiz7 requested changes
Code Review: 🔴 

Check suggestions

2022-09-20 11:58 UTC, AlexRuiz7 commented on server/routes/wazuh-api.ts
> +    path: '/api/get-logos',
No need to add the action (HTTP verb) to the URL, it's already defined in the route (get).

It's not a good practice to do this, check guideline nr.1 from this [Best Practices for naming REST API endpoints](https://betterprogramming.pub/10-best-practices-for-naming-rest-api-endpoints-442ae592a3a0) guide.

2022-09-20 11:58 UTC, AlexRuiz7 commented on server/routes/wazuh-api.ts
> +    path: '/api/get-logos',
As @asteriscos is on holidays, I'll apply this change.

2022-09-20 12:11 UTC, AlexRuiz7 approved these changes
LGTM!

2022-09-20 12:11 UTC, AlexRuiz7 commented on server/routes/wazuh-api.ts
> +    path: '/api/get-logos',
Solved in https://github.com/wazuh/wazuh-kibana-app/pull/4539/commits/0ace60f0912eb2fb9363999ba9180ffc135486f0

2022-09-20 12:21 UTC, merged

2022-09-20 12:29 UTC, AlexRuiz7 commented
Backports successfully merged