pagination SCA table
wazuh/wazuh-kibana-app pull request #4653
Opened 2022-10-06 13:04 UTC by chantal-kelm

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2022-10-12 17:29 UTC, Machi3mfl commented
## Researching the current issue

Researching the behavior of the `search bar` and `table` in the `SCA > Inventory` view.
1. The search bar builds the suggestions list calling to the `/sca/AGENT_ID/checks/POLICY_ID}` endpoint retrieving all the checks by policy and making a distinct manually in the `loadScaPolicy` and `buildSuggestionSearchBar` methods.
2. The view uses de `TableWzAPI` to render the table. 

### Steps

- Use the SCA endpoint with the distinct params to prevent requesting all the data needlessly.
- Improve the `inventory.tsx` file because have too much logic and is incomprehensible. It's better to create more files (components) to make the component more readable and reusable.

2022-10-12 17:30 UTC, Machi3mfl commented
I found and resolved an error in the `Vulnerabilities > Inventory.` This error was generated by the removed `beautifyDate` function. 

![Selection_067](https://user-images.githubusercontent.com/6089438/195406671-e4dfdc4f-8b23-4268-ab33-ce29277beb4e.png).

2022-10-17 13:16 UTC, Desvelao commented on public/components/agents/vuls/inventory.tsx
> -  }
**question**: why is it removed?

2022-10-17 17:21 UTC, Machi3mfl commented on public/components/agents/vuls/inventory.tsx
> -  }
Solved

2022-10-18 14:48 UTC, AlexRuiz7 commented on public/components/common/tables/table-wz-api.tsx
> +  reload?: any;
Isn't it boolean?

2022-10-18 14:51 UTC, AlexRuiz7 commented on public/components/agents/sca/inventory/lib/api-request.ts
> +  format = (item) => item
Types?

2022-10-18 14:54 UTC, AlexRuiz7 commented on public/components/agents/vuls/inventory.tsx
> +  // when vulne_isMoun
Leftover comments

2022-10-18 16:18 UTC, Machi3mfl commented on public/components/agents/sca/inventory/lib/api-request.ts
> +  format = (item) => item
Solved in the last commit

2022-10-18 16:18 UTC, Machi3mfl commented on public/components/agents/vuls/inventory.tsx
> +  // when vulne_isMoun
Solved in the last commit

2022-10-18 20:45 UTC, Mayons95 requested changes
After testing this feature, we can identify that the search bar has some problems.

![image](https://user-images.githubusercontent.com/104914131/196540873-f5bac3b7-5dde-490e-b9ce-a8da6dbe90e4.png)

Here I applied a tittle filter and it's ignored by the filter bar.
@Machi3mfl There is a possibility to check this ?

2022-10-19 13:45 UTC, Mayons95 commented
After reviewing the functionallity with @Machi3mfl we found that the environment API was outdated, after download the changes we could check that the filter bar it's working fine.
I left here the evidence

<details>

![Screenshot from 2022-10-19 10-42-57](https://user-images.githubusercontent.com/104914131/196708905-e99d5521-41d9-4b72-ab9a-6484e942fa38.png)


</details>

2022-10-19 13:47 UTC, Mayons95 approved these changes
LGTM
TR: :heavy_check_mark:

2022-10-19 14:56 UTC, AlexRuiz7 approved these changes
LGTM!

2022-10-19 15:04 UTC, merged