Creating a new feature
wazuh/wazuh-kibana-app pull request #4822
Opened 2022-11-07 20:51 UTC by Mayons95

Hi team ! I create this PR to add a new test case to cover the unpin functionality from the agent module dashboard.
I'm working on reusing some existing functionality. I'll add more info as soon I advance with the development

2022-11-08 19:27 UTC, Mayons95 commented
![image](https://user-images.githubusercontent.com/104914131/200656812-892f06a1-2e40-4b82-91d5-fa797797dfc5.png)

I found this selector that it's broken. I'm working to fix it and run the complete test execution

2022-11-09 17:48 UTC, Mayons95 commented
Test it's working for WZD
![Uploading Screenshot from 2022-11-09 14-45-13.png…]()

2022-11-09 18:28 UTC, asteriscos requested changes
Please review a few typos.

2022-11-09 18:28 UTC, asteriscos commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +  in order to aplly it across the modules
There's a typo in "apply"

2022-11-09 18:28 UTC, asteriscos commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +    And The user unppined the selected filter
There's a typo in "unpinned"

2022-11-09 18:28 UTC, asteriscos commented on test/cypress/cypress/integration/step-definitions/filters/the-user-unppined-the-selected-filter-when.js
> +When('The user unppined the selected filter', () => {
There's a typo in "unpinned"

2022-11-09 19:31 UTC, Mayons95 commented
WZD report generated:
[Uploading WZD-09-11.pdf…]()

2022-11-09 19:42 UTC, Mayons95 commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +  in order to aplly it across the modules
Done

2022-11-09 19:42 UTC, Mayons95 commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +    And The user unppined the selected filter
Done

2022-11-09 19:42 UTC, Mayons95 commented on test/cypress/cypress/integration/step-definitions/filters/the-user-unppined-the-selected-filter-when.js
> +When('The user unppined the selected filter', () => {
Done

2022-11-10 08:52 UTC, AlexRuiz7 commented on test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-events.feature
>  Feature: Validate that the added filter label is remove after click remove filter option agent modules Dashboard
This sentence is so hard to understand

2022-11-10 08:52 UTC, AlexRuiz7 commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +  I want to unppined a filter
I want to **unpin**

2022-11-10 08:52 UTC, AlexRuiz7 commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +  Scenario Outline: The user add and pin new filer - across the modules - from dashboard to event page <Module Name>
The user add**s** and pin**s** **the** new filter

2022-11-10 08:52 UTC, AlexRuiz7 commented on test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
> +    And The user unpinned the selected filter
And the user unpin**s**

2022-11-10 12:59 UTC, asteriscos approved these changes
LGTM :heavy_check_mark:

2022-11-14 13:20 UTC, AlexRuiz7 approved these changes

2022-11-14 13:20 UTC, merged