show name + number in OS version
wazuh/wazuh-kibana-app pull request #4851
Opened 2022-11-11 17:11 UTC by chantal-kelm

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2022-11-11 17:19 UTC, asteriscos requested changes
should this have a changelog entry?

2022-11-11 17:26 UTC, Tostti approved these changes
LGTM

2022-11-11 17:28 UTC, asteriscos approved these changes
LGTM: :heavy_check_mark:

2022-11-11 17:28 UTC, asteriscos commented on CHANGELOG.md
> +- Show name + number in OS version. [#4851](https://github.com/wazuh/wazuh-kibana-app/pull/4851)
**Nitpick:**
The changelog entry could be a little more verbose, so anyone can understand easily what has changed.

Maybe something like:
_"Show OS name and OS version in the agent installation wizard."_

2022-11-14 09:52 UTC, asteriscos approved these changes
LGTM :heavy_check_mark:

2022-11-14 11:31 UTC, Tostti approved these changes
LGTM

2022-11-14 11:33 UTC, merged