Disable synced by default
wazuh/wazuh-kibana-app pull request #5143
Opened 2023-01-19 16:55 UTC by asteriscos

### Description
Hi team,

This PR disables by default the `synced` field of the Agents table and removes the metric on the top of the view. Even though it is disabled, it still can be enabled by checking the field in the table settings.
 
### Issues Resolved
Closes #5141 

### Evidence
![image](https://user-images.githubusercontent.com/9343732/213504765-d391e7ee-4e5d-4d21-b033-a38cd57a224b.png)

### Test

- Register agents in the manager
- Go to Agents overview
- Check the table does not include the `synced` field
- Check the top metrics don't include the `Synced` percentage
- Check the synced field can be enabled in the Agents table

>  **Important**
> To test it properly, delete the preview _**local storage**_ table configuration
>  ![image](https://user-images.githubusercontent.com/9343732/213504621-531845cd-3485-4856-8e62-8b6c16ca1518.png)

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-01-19 18:58 UTC, Tostti requested changes
According to the [Issue](https://github.com/wazuh/wazuh-kibana-app/issues/5141), the `Registration date` and `Last keep alive` fields should also be disabled by default

2023-01-24 07:38 UTC, Desvelao commented on public/components/management/cluster/node-list.tsx
> +                name: 'IP Address',
**nitpick**: The other references use `IP address` with `address` in lowercase. Is there a reason to this case is different?

2023-01-24 08:52 UTC, Desvelao requested changes
**nitpick**: There are more files that contain references to IP and OS that we could be interested to change too.

Some of them:
- common/csv-key-equivalence.ts
- public/components/overview/office-panel/config/main-view-config.tsx
- public/components/visualize/visualizations.js (IP by Users)
- public/controllers/management/components/management/configuration/global-configuration/global-configuration-remote.js
- public/templates/management/management.html
- server/controllers/wazuh-reporting.ts
- server/integration-files/visualizations/overview/overview-hipaa.ts
- server/integration-files/visualizations/overview/overview-office.ts
- common/csv-key-equivalence.ts Review where it is affecting to
- common/compliance-requirements/pci-requirements.ts Not sure if this we could change it or should not changed.
- public/controllers/agent/components/agents-table.js
- public/controllers/management/components/management/configuration/vulnerabilities/vulnerabilities-providers.js
- public/controllers/overview/components/overview-actions/agents-selection-table.js
- server/lib/reporting/agent-configuration.ts
- server/lib/reporting/extended-information.ts
- public/controllers/management/components/management/groups/group-agents-table.js

Fix:
- public/components/management/cluster/node-list.tsx
- public/controllers/management/components/management/status/status-agent-info.js

2023-01-24 11:17 UTC, asteriscos commented
> **nitpick**: There are more files that contain references to IP and OS that we could be interested to change too.
> 
> Some of them:
> 
> * common/csv-key-equivalence.ts
> * public/components/overview/office-panel/config/main-view-config.tsx
> * public/components/visualize/visualizations.js (IP by Users)
> * public/controllers/management/components/management/configuration/global-configuration/global-configuration-remote.js
> * public/templates/management/management.html
> * server/controllers/wazuh-reporting.ts
> * server/integration-files/visualizations/overview/overview-hipaa.ts

None found

> * server/integration-files/visualizations/overview/overview-office.ts

None found

> * common/csv-key-equivalence.ts Review where it is affecting to
> * common/compliance-requirements/pci-requirements.ts Not sure if this we could change it or should not changed.
> * public/controllers/agent/components/agents-table.js
> * public/controllers/management/components/management/configuration/vulnerabilities/vulnerabilities-providers.js

The space is too small and reducing "Operating system" to "OS" is worthwhile

> * public/controllers/overview/components/overview-actions/agents-selection-table.js
> * server/lib/reporting/agent-configuration.ts
> * server/lib/reporting/extended-information.ts

The "OS" in line 84 is justified to optimize the table space, as the manager name or agent name can be quite lengthy.

> * public/controllers/management/components/management/groups/group-agents-table.js
> 
> Fix:
> 
> * public/components/management/cluster/node-list.tsx
> * public/controllers/management/components/management/status/status-agent-info.js


Thanks for the suggestions.

2023-01-24 11:46 UTC, Tostti approved these changes
TEST:✔️
CR:✔️
PREVIOUS REVIEW CHANGES REQUESTED: ✔️

Evidence: 
![imagen](https://user-images.githubusercontent.com/42900763/214283525-b5f943f8-e09d-4489-b3a6-9abb6f6e0786.png)
![imagen](https://user-images.githubusercontent.com/42900763/214283656-9631a5a2-7676-44ce-98a2-a0b0d0a49adc.png)
![imagen](https://user-images.githubusercontent.com/42900763/214283660-5b343eba-8f45-4cc2-90f5-8fe0488cfe39.png)


LGTM

2023-01-24 12:30 UTC, AlexRuiz7 approved these changes
LGTM

2023-01-24 17:57 UTC, asteriscos commented
## Table design 

The proposal to optimize the agents table is to make use of the **euiBasicTable** property` table-layout="auto"` and remove the fixed widths. Setting the table layout to auto make much better use of the blank spaced in columns in favor of lengthy column values. 

### side effect
The` table-layout="auto`" prop doesn't support truncating text when the table width is limited by the viewport. To avoid overflowing the table it wraps the lines of the values.

2023-01-25 11:27 UTC, Tostti approved these changes
![imagen](https://user-images.githubusercontent.com/42900763/214550563-35604013-ddaa-49de-a9f8-fee1c97f60f3.png)
![imagen](https://user-images.githubusercontent.com/42900763/214550600-b1094951-d5e9-4646-964c-6ee81cfc377b.png)
![imagen](https://user-images.githubusercontent.com/42900763/214550678-ca59727c-1ab1-48d2-acb5-089da4d00fd5.png)

![imagen](https://user-images.githubusercontent.com/42900763/214550425-64872573-2fd0-4235-a969-9774f52cea83.png)

TEST:✔️
CR:✔️

LGTM

2023-01-25 13:57 UTC, chantal-kelm commented
**Replace OS to Operating system and IP to IP address**

**Agents table** 🟢 

<details>

**Chrome**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214559474-accd464e-9cc5-4711-a0ee-d62fe4b70cce.png">

**Firefox**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214558343-286cbd6f-5a07-4b9d-aea0-863a0934cf17.png">

**Safari**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214559886-96616510-3641-4377-b115-fdd0cdbc9698.png">
</details>

**Agents Inventory PDF report**

<details>

**Chrome**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214560350-9d394ada-8d21-424e-a13a-fe1b8d4107de.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214560711-7a1728f0-44fd-4425-badf-aa4a13d4d738.png">

**Firefox**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214560980-eb78c564-3d39-4502-886a-a8ef9d185cc9.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214561127-13c77b45-c445-4acf-8775-e5129e4cc647.png">

**Safari**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214561319-ee28507d-e76d-43a6-bac1-064a7473b9ba.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214561395-24c98da4-5d8b-4991-b4f0-14e715e8c25f.png">

</details>

**Groups agents table** 🟢 

<details>

**Chrome**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214562173-622bdd11-fb99-4986-bbf4-ad5b6869a082.png">

**Firefox** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214562281-453d3470-4cba-4d07-a386-e8c7b28ead6e.png">

**Safari** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214562414-64dfa5eb-0a99-4e9e-8505-328c2f70ad87.png">
</details>

**Agent overview** 🟢 

<details>

**Chrome** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214562676-91ec6da1-4d1a-4961-948a-8230407006c2.png">

**Firefox** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214562833-e295cf92-5c86-429d-bfc8-512fce142a3e.png">

**Safari** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214562975-5a346f4b-de3e-47f1-a357-5f192a5cb180.png">

</details>

**Management cluster** 🟢 

<details>

**Chrome**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214563248-21341ff7-c334-424c-b063-3ad91dad630a.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214565177-a29d2db4-2f1e-48ae-b754-e3632f5c6954.png">

**Firefox** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214565232-31b250c5-4e35-4d59-af8f-6c94b7ac3c7c.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214565263-0757b16b-298b-4d6b-9de0-9659268c3b3d.png">

**Safari** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214565354-754e9664-7987-4996-b6ef-2f817d1bbb77.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214565392-61944117-e47a-4c47-8fce-cd827d01ff39.png">

</details>

**Office365 Panel** 🟢 

<details>

**Chrome**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214565854-c5ada8f8-1576-4ea6-b226-d4421ec06ddc.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566002-9c5f2426-c189-426b-9f3e-0e90295f2b29.png">

**Firefox** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566141-edb229d3-c5a5-42dc-8621-d31ec3e32fd1.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566178-847b3c35-4058-4a95-b759-74c32c7db2c6.png">

**Safari** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566326-5f95301c-ae11-4908-b036-066f48a11faa.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566352-b32909ae-cfb0-42ab-a237-249539d7fec5.png">

</details>

**Global Configuration Remote** 🟢 

<details>

**Chrome** 🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566636-67893191-d0d5-4960-bf7e-9469f62a77ab.png">

**Firefox**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566719-cc680f70-642f-42af-9802-5a3e8cd70d98.png">

**Safari**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214566788-d1767438-2c42-4b63-afb9-679b46efe547.png">

</details>

**Explore Agent modal** 🟢 

<details>

**Chrome**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214567064-209eadb3-c598-4944-aaa5-025bafa6a997.png">

**Firefox**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214567178-14f31b10-4530-4acc-8c2b-e5ea1aa6422d.png">

**Safari**  🟢 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214567270-1b9ce56c-5ee7-4e3b-9c4c-9ab21042dc84.png">

</details>

**Redistribute Agents Table column widths automatically** 🔴 

<details>

**Chrome**  🔴 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214577304-e52aacf6-17fe-49e9-ba2d-03e7d71bbeb9.png">

**Firefox** 🔴 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214577463-eed27bdf-4266-43f0-8d6b-68457f6fc39e.png">

**Safari** 🔴  

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214579993-fe1c8132-e7ab-4059-a954-e00d8fdfba4b.png">

</details>

2023-01-25 15:37 UTC, asteriscos commented
> 

Thanks for reporting this. I allowed the Registration date, IP address and version columns to wrap the line to prevent the table overflow.

![image](https://user-images.githubusercontent.com/9343732/214606674-d92002eb-a399-462b-a233-af8b34c9faab.png)

2023-01-25 18:34 UTC, chantal-kelm commented
> > 
> 
> Thanks for reporting this. I allowed the Registration date, IP address and version columns to wrap the line to prevent the table overflow.
> 
> ![image](https://user-images.githubusercontent.com/9343732/214606674-d92002eb-a399-462b-a233-af8b34c9faab.png)

Chrome

<details>

The table with all columns added looks good from 864px width onwards

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214647616-8ce84917-ac84-479a-8d7b-fbc894d723bc.png">

</details>

Firefox

<details>
The table with all columns added looks good from 854px width onwards

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214648094-16c1c0a0-17ff-4ba8-9b82-876a0e90dd2a.png">

</details>

Safari

<details>

The table with all columns added looks good from 854px width onwards

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214648738-f7de23dc-6c72-45fa-bfaa-55d30c4913e3.png">

</details>

2023-01-25 18:34 UTC, chantal-kelm approved these changes
CR: ✅ 
TEST: ✅ 

Chrome

<details>

The table with all columns added looks good from 864px width onwards

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214647616-8ce84917-ac84-479a-8d7b-fbc894d723bc.png">

</details>

Firefox

<details>
The table with all columns added looks good from 854px width onwards

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214648094-16c1c0a0-17ff-4ba8-9b82-876a0e90dd2a.png">

</details>

Safari

<details>

The table with all columns added looks good from 854px width onwards

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/99441266/214648738-f7de23dc-6c72-45fa-bfaa-55d30c4913e3.png">

</details>

2023-01-25 19:29 UTC, Tostti approved these changes
Chrome

<details>
The table looks good in all the resolutions. When the is smaller than the width, it enables lateral scroll.

![imagen](https://user-images.githubusercontent.com/42900763/214667713-f078ba3c-75a5-43cc-93d0-c303764239b6.png)

![imagen](https://user-images.githubusercontent.com/42900763/214667619-5c1606c3-8dce-459f-b4e5-3aee4c4ff0ae.png)

</details>

Firefox

<details>
The table looks good in all the resolutions. When the is smaller than the width, it enables lateral scroll.

![imagen](https://user-images.githubusercontent.com/42900763/214666091-601151b4-19b8-4a8d-b504-b7fbc865a416.png)

![imagen](https://user-images.githubusercontent.com/42900763/214666368-78c1e506-92a8-4c86-88a5-4f27836dcaa9.png)


</details>





TEST:✔️
CR:✔️

LGTM

2023-01-26 13:29 UTC, Desvelao approved these changes

2023-01-26 13:30 UTC, merged