Add `rel="noopener noreferrer"` in documentation links
wazuh/wazuh-kibana-app pull request #5197
Opened 2023-02-07 10:34 UTC by yenienserrano

### Description
the `rel="noopener noreferrer"` attribute is added to external links
 
### Issues Resolved

- #5038 

### Evidence

![image](https://user-images.githubusercontent.com/63758389/217221009-d41851c7-eb37-4e47-9d3e-8930cb4343a7.png)
![image](https://user-images.githubusercontent.com/63758389/217221108-bd9cee73-0d2f-468f-a2e8-a18240588522.png)
![image](https://user-images.githubusercontent.com/63758389/217221161-0578245b-c16d-41bf-96ac-9a9db9703779.png)

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-02-09 10:24 UTC, AlexRuiz7 requested changes

2023-02-09 10:24 UTC, AlexRuiz7 commented on CHANGELOG.md
> +- Add rel="noopener noreferrer" in documentation links. [#5197](https://github.com/wazuh/wazuh-kibana-app/pull/5197)
ChangeLog entries must always use past tense (Add → Added).

2023-02-20 11:38 UTC, Desvelao commented
CodeQL scan: https://github.com/wazuh/wazuh-kibana-app/actions/runs/4222981621

2023-02-20 12:35 UTC, Desvelao commented
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Check the value of attributes in changed anchors containing noopener noreferer | :green_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Check the value of attributes in changed anchors containing noopener noreferer</summary>

Chrome - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/220106183-af624ca1-15bc-4acb-888d-8d5e8205b904.png)
![image](https://user-images.githubusercontent.com/34042064/220107952-35aabc7a-2d67-4371-b7e3-b538fdc057ce.png)
![image](https://user-images.githubusercontent.com/34042064/220108831-4cbebd40-2bd0-4327-b63c-fa78714938c6.png)
![image](https://user-images.githubusercontent.com/34042064/220109100-1ebe7a15-595c-46b9-8f9c-1653f1c0fcd5.png)
Firefox - :black_circle:

Safari - :black_circle:

</details>

2023-02-20 12:36 UTC, Desvelao approved these changes
**review**

:green_circle: code
:green_circle: test

2023-02-23 09:24 UTC, AlexRuiz7 approved these changes

2023-02-23 14:04 UTC, merged