Change link to Malware detection documentation
wazuh/wazuh-kibana-app pull request #5329
Opened 2023-03-28 15:02 UTC by yenienserrano

### Description
Anomaly and malware detection link changed to malware detection link. Due to documentation changes in this [PR](https://github.com/wazuh/wazuh-documentation/pull/5944)
 
### Issues Resolved
- 5318

### Evidence

![image](https://user-images.githubusercontent.com/63758389/228280222-77680871-8279-4ae5-858c-6a44bc83928b.png)

### Test

1. Navigate to management/configuration/policy monitoring/system audit
2. Click on image ![image](https://user-images.githubusercontent.com/63758389/227267718-afe190b4-05ac-4d8e-b3d8-3480de25e135.png)
3. The button is now called `Malware detection` and the href has to be `user-manual/capabilities/malware-detection/index`.

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-03-29 11:31 UTC, AlexRuiz7 requested changes

2023-03-29 11:31 UTC, AlexRuiz7 commented on CHANGELOG.md
> +
Move to `Fixed`

2023-03-29 14:48 UTC, AlexRuiz7 approved these changes

2023-03-30 07:24 UTC, Desvelao commented
# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox |
| --- |  --- | --- |
| The link with the title Malware detection of Management/Configuration/Policy monitoring should open a working page | :green_circle: | :green_circle: |
| The link with the title Malware detection of Agents/{agent}/Configuration/Policy monitoring should open a working page | :green_circle: | :green_circle: |

**Details**
<details>
<summary>:green_circle: The link with the title Malware detection of Management/Configuration/Policy monitoring should open a working page</summary>

Chrome - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/228760449-ea7d9677-be0b-4f83-8a99-dc255c49a108.png)

Firefox - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/228759361-5d1540bf-d44c-4ccb-a413-c40ee05da5a8.png)

</details>

<details>
<summary>:green_circle: The link with the title Malware detection of Agents/{agent}/Configuration/Policy monitoring should open a working page</summary>

Chrome - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/228760579-0ec1147e-78d4-4878-9239-70127234e327.png)

Firefox - :green_circle:
![image](https://user-images.githubusercontent.com/34042064/228759883-323ee4d9-da30-4851-b51a-2a2a701a41ea.png)

</details>

2023-03-30 07:24 UTC, Desvelao approved these changes
**review**

:green_circle: code
:green_circle: test https://github.com/wazuh/wazuh-kibana-app/pull/5329#issuecomment-1489821807

2023-03-30 09:00 UTC, AlexRuiz7 approved these changes

2023-03-30 09:45 UTC, merged