Replace search bar on TableWzAPI component
wazuh/wazuh-kibana-app pull request #5442
Opened 2023-05-15 07:46 UTC by Desvelao

### Description
This pull request replace the search bar on the TableWzAPI component and each usage of this.

### Issues Resolved
[List any issues this PR will resolve]

### Evidence
[Provide screenshots or videos to prove this PR solves the issues]

### Test
[Provide instructions to test this PR]

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

2023-08-01 15:34 UTC, asteriscos requested changes
Test: :x: 

If I click on the groups filter in the flyout, it adds the field `group` and the input marks it as an invalid field. It seems the suggestions array has `groups` field as plural and it should be singular.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/9343732/a0c6633f-452a-45fd-805b-08be3923d205)

2023-08-02 11:14 UTC, Desvelao commented on plugins/main/public/controllers/management/components/management/ruleset/components/ruleset-suggestions.ts
> +      { label: 'filename', description: 'filter by filename' },
Fixed in https://github.com/wazuh/wazuh-kibana-app/pull/5442/commits/0696698c358441ad2589d0f6e7faf83dad446fec.

2023-08-02 11:14 UTC, Desvelao commented on plugins/main/public/controllers/management/components/management/ruleset/components/ruleset-table.tsx
>        downloadCsv={true}
Fixed in https://github.com/wazuh/wazuh-kibana-app/pull/5442/commits/0696698c358441ad2589d0f6e7faf83dad446fec.

2023-08-02 11:14 UTC, Desvelao commented on plugins/main/public/controllers/management/components/management/ruleset/components/ruleset-table.tsx
>        downloadCsv={true}
Fixed in https://github.com/wazuh/wazuh-kibana-app/pull/5442/commits/0696698c358441ad2589d0f6e7faf83dad446fec.

2023-08-02 11:15 UTC, Desvelao commented
> If I click on the groups filter in the flyout, it adds the field group and the input marks it as an invalid field. It seems the suggestions array has groups field as plural and it should be singular.

The field name for `q` is `groups` in plural.

The `group` suggestion of the old search bar is due this used the `group` query parameter instead a field of `q` query parameter.

2023-08-04 07:33 UTC, Desvelao commented
# Changes
- Remove the double toast message when there is an error in the API request to fetch the data in the TableWzAPI component
- Rename the error name to RequestError to hide AxiosError when there is an error fetching the data in the TableWzAPI component

2023-08-07 07:53 UTC, Desvelao commented
# Compare

| query type | query (NEW) | OLD | NEW | Commnent |
| --- | --- | --- | --- | --- |
| term | syslog | :green_circle: | :green_circle: | |
| term | CC7.3 | :green_circle: | :green_circle:  | |
| term | duplicate IP | :green_circle: | :green_circle: | OLD: incase-sensitive (`duplicate ip` gives the same results). NEW: case-sensitive. |
| field | group=AeD | :green_circle: | :green_circle: | |

2023-08-08 10:26 UTC, Desvelao commented
# Changes

- Add a workaround to the value suggestions. It will only display the values that match the validation regular expression. This mitigates the problems caused when using these values, and they don't match the validation, avoiding the search can be run. Related to https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1669348763.

2023-08-09 09:47 UTC, yenienserrano commented
### Test

> Use a Wazuh manager

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Modules > Security Configuration Assessment > {policy_id} > Checks: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Type a simple field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Type a complex field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Click in the result KPI, it should add a filter to the search bar and the table should be filtered | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Type a simple field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Type a complex field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Click in the package name of Summary panel, it should add a filter to the search bar and the table should be filtered | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Click in the severity KPI of panel, it should add a filter to the search bar and the table should be filtered | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Type a simple field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Type a complex field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Decoders: For each suggested field, check the value suggestion display results or at least doesn [...]

2023-08-09 11:42 UTC, JuanGarriuz commented
# Test

> Use a Wazuh manager

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Modules > Security Configuration Assessment > {policy_id} > Checks: For each suggested field, check the value suggestion display results or at least doesn't break | 🟡 | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Using a value suggested should allow to run the search | ⚫  | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Type a term and run the search should search in each displayed field | ⚫   | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Type a simple field search and this should return the expected results | ⚫   | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Type a complex field search and this should return the expected results | ⚫   | :black_circle: | :black_circle: |
| Modules > Security Configuration Assessment > {policy_id} > Checks: Click in the result KPI, it should add a filter to the search bar and the table should be filtered | ⚫   | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: For each suggested field, check the value suggestion display results or at least doesn't break | ⚫   | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Using a value suggested should allow to run the search | ⚫  | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Type a simple field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Type a complex field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Click in the package name of Summary panel, it should add a filter to the search bar and the table should be filtered | :black_circle: | :black_circle: | :black_circle: |
| Modules > Vulnerabilities > Inventory: Click in the severity KPI of panel, it should add a filter to the search bar and the table should be filtered | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Type a simple field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Groups: Type a complex field search and this should return the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Mitigations: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Software: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Tactics: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Modules > MITRE ATT&CK > Intelligence > Techniques: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Using a value suggested should allow to run the search | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Type a term and run the search should search in each displayed field | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Type a simple field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > CDB Lists: Type a complex field search and this should returns the expected results | :black_circle: | :black_circle: | :black_circle: |
| Management > Decoders: For each suggested field, check the value suggestion display results or at least doesn't break | :black_circle: | :black_circle: | :black_circle: |
| Management > Decoders: Using a [...]

2023-08-10 14:30 UTC, yenienserrano approved these changes
LGTM
Test: https://github.com/wazuh/wazuh-kibana-app/pull/5442#issuecomment-1671010616

2023-08-11 08:48 UTC, JuanGarriuz approved these changes
LGTM
Tests: https://github.com/wazuh/wazuh-kibana-app/pull/5442#issuecomment-1671170727

2023-08-11 13:17 UTC, asteriscos approved these changes

2023-08-11 13:22 UTC, merged