Create incident response dashboard
wazuh/wazuh-kibana-app pull request #5934
Opened 2023-09-26 12:54 UTC by chantal-kelm

### Description

Create incident response dashboard
 
### Issues Resolved

#5933 

### Evidence

<img width="1792" alt="image" src="https://github.com/wazuh/wazuh-kibana-app/assets/99441266/15673396-0818-4b97-b2f5-812e12dadbf2">

### Test

Import the following dashboard and check that the dashboard is the same as the one shown in this PR.

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

2023-09-26 14:43 UTC, jbiset requested changes
## CR: :yellow_circle:  (Commented)

## UI Test :green_circle: 

![Evidence_Light](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/e6de5e2a-10d0-4146-8c69-fe0b294d565a)

![Evidence_Dark](https://github.com/wazuh/wazuh-kibana-app/assets/43619595/1b780de9-ec11-4c0f-8ed8-649e309fe084)

2023-09-26 14:43 UTC, jbiset commented on CHANGELOG.md
> +- Create the incident response dashboard.[5934](https://github.com/wazuh/wazuh-kibana-app/pull/5934)
Missing `#` on `[5934]`

2023-09-26 16:38 UTC, jbiset approved these changes

2023-09-29 12:56 UTC, lucianogorza commented
## CR: :green_circle: 

## UI Test :green_circle: 

![Light](https://github.com/wazuh/wazuh-kibana-app/assets/103193307/9035e1e3-b1a3-48f2-ada0-6563622ec0a4)

![Dark](https://github.com/wazuh/wazuh-kibana-app/assets/103193307/d6647068-0ee4-4038-91ef-a60634ddace8)

2023-09-29 12:57 UTC, lucianogorza approved these changes

2023-09-29 12:59 UTC, merged